### ISSUE TITLE
Could you add subdomain to main domain function ?

### ISSUE THREAD

**Issue by mooms06** [jokokko/breadcrumbus#3]
Hi,

With Firefox 56 and below, I used Advanced Location bar, and it allowed to click on the main domain when we where on a subdomain, now with Firefox 57 and up I'm willing to use your extension as a replacement, but a feature is missing:

 Example: on `https://addons.mozilla.org/firefox/addon/breadcrumbus/` we should have the possibility to go to `mozilla.org` and it should be on top of all other choices.

Also, could you add an option to open it in a new tab instead of the current tab ?

Regards.

**Comment by jokokko** [comment]
Hello. 

Thanks for the suggestions. I think I can work them in. Opening in new tab should already work with mouse middle click. But I'll see if the context menu can be fixed too (now that it seems to be working on the panels).

**Comment by mooms06** [comment]
Hi, 
It works, but not exactly as it should, in the same example URL, I think `mozilla.org` should be on top because its the main domain, and the domain below should be named `addons.mozilla.org` to avoid any confusions.
![breadcrumbus](https://user-images.githubusercontent.com/25405517/32922844-93ec8836-cb34-11e7-98aa-43e7d8628bd0.png)
