### ISSUE TITLE
Not working correctly on http://ftp.mozilla.org/

### ISSUE THREAD

**Issue by mooms06** [jokokko/breadcrumbus#4]
Try to use Breadcrumbus on http://ftp.mozilla.org/pub/firefox/candidates/57.0-candidates/build3/ 
Because it remove the ending `/` you will encounter a `404 not found`.

**Comment by jokokko** [comment]
Thanks once again for bringing another deficiency to my attention. A lazy oversight on my behalf on constructing the last URI segment. I'll fix it.

**Comment by mooms06** [comment]
good !

**Comment by jokokko** [comment]
Hullo,

Should finally be fixed on 1.0.5 (once published). Sorry it took me a long time, but life's been keeping me busy.

I appreciate the feedack.

**Comment by mooms06** [comment]
Thanks, I hope you will also add the new icon in 1.0.5 !
