### ISSUE TITLE
[Suggestion] Add a nicer icon ?

### ISSUE THREAD

**Issue by mooms06** [jokokko/breadcrumbus#5]
Right now the icon in the url bar is a bit misleading, the `B` looks like a `E`.
I'm not a graphic designer,  but I think something like [this](https://www.google.fr/search?q=icone+url&tbm=isch&tbs=rimg:CQjlcXFBe7lAIjiZ6WCZ4vuzNPK50FGbZpHP9EV3uBJqd49WAMZPmTKxI57ReMDAkW0RNm9uX4j6bdNG3jCgt6uIlSoSCZnpYJni-7M0EfC2btDeMTaQKhIJ8rnQUZtmkc8RStX-PWHFxB0qEgn0RXe4Emp3jxHkDbzOYJIQ1yoSCVYAxk-ZMrEjEQbLLDPZdc0eKhIJntF4wMCRbRERah7z1cmHxGwqEgk2b25fiPpt0xGOft_14sEd0rSoSCUbeMKC3q4iVEYbmZiQRSurI&tbo=u&sa=X&biw=1023&bih=652&dpr=1.5) or [that](https://www.google.fr/imgres?imgurl=https://i.stack.imgur.com/Qs3i1.png&imgrefurl=https://tex.stackexchange.com/questions/22536/what-symbol-can-be-used-in-front-of-a-url&docid=dUS6f422v-38YM&tbnid=QRSKxFGApEU_FM:&vet=10ahUKEwjl_N7Bq8TXAhXQyRoKHVOGCDEQMwhXKCgwKA..i&w=121&h=111&bih=652&biw=1023&q=icone%20url&iact=mrc&uact=8) should be better.

**Comment by jokokko** [comment]
I understand - Given I have zero artistic talent myself, I just took two letters (the initials, unsurprisingly) and made it monochrome. Although I created the extension to serve my personal browsing needs, I tried to avoid public domain icons, so as not to confuse anybody or risk conflicting existing or future extensions.

Once again, the feedback is appreciated.

**Comment by mooms06** [comment]
I see, but I don't understand why you wouldn't use a public domain icon, they are there for that.
Conflicting with other extensions don't seems likely, and not a big deal to me, because right now your extension is unique in its features if I'm not mistaken.
If you truly want an unique icon, you could ask here and on the AMO page of your extension, maybe someone in your users have some graphic skills !

**Comment by mooms06** [comment]
Here is a free icon I resized to 32x32, what do you think ?

![icon-32-bw](https://user-images.githubusercontent.com/25405517/33039791-81cfa6c6-ce39-11e7-9abf-26f1dfc99fa9.png)

The source is [here](https://pixabay.com/fr/lien-url-ic%C3%B4ne-cha%C3%AEnes-web-1271843/).

**Comment by jokokko** [comment]
I'll see about making the icon set themeable, i.e. allow switching icons. The linked icon seems solid attribution-wise, so then it could be used. Feedback again greatly appreciated.

**Comment by dionymnia** [comment]
I just added Breadcrumbus, which does exactly what I wanted and had previously used Location Bar Enhancer for. I wanted to chime in and agree with mooms06, that a visual icon would be excellent - the chain link image would be perfect. It's not a dealbreaker, but I just figured I'd let you know that I'd love the icon change as well!

Again, I really like Breadcrumbus - thank you for sharing it!

**Comment by jokokko** [comment]
Added support for theming in 1.0.5. One alternative theme with chain link icons added to complement the original icons (done by yours truly, in a matter of a few minutes).
