### ISSUE TITLE
Not open new tab in the same container

### ISSUE THREAD

**Issue by banhgao** [jokokko/breadcrumbus#7]
When opening a new tab (middle clicking the breadcrumb), it is opened in the default container, not the container I'm using.

**Comment by jokokko** [comment]
Ah, an oversight from myself (personally not using container tabs yet). I'll see if I can address this with the next update (if the extension API supports this or honours containers).

Thanks for reporting it!

**Comment by jokokko** [comment]
Ta. Should be fixed with 1.0.5. (Note to self: start using container tabs).
