### ISSUE TITLE
About:* shows as null

### ISSUE THREAD

**Issue by jerone** [jokokko/breadcrumbus#9]
Opening an About-page shows the protocol as `null`. See screenshot of [`about:addons`](about:addons):
![2018-01-01 19_17_22-](https://user-images.githubusercontent.com/55841/34469976-6eb0617e-ef28-11e7-845b-aa6d8d5c48a2.png)

**Comment by jerone** [comment]
I [updated the code](https://github.com/jerone/breadcrumbus/commit/ef3472ab120dae5b16e1ddbbafba103549bf803e) to detect `about:*` and not show as `null`. 

But when opening an `about:*` uri, i got JavaScript errors: `Error: Illegal URL: about:about`. After some investigating, I found out that it's not possible to open `about:*` at all: https://bugzilla.mozilla.org/show_bug.cgi?id=1269456

Personally I think there are two ways to solve:
1. Disable the extension completely on `about:*` pages.
2. Implement https://github.com/jerone/breadcrumbus/commit/ef3472ab120dae5b16e1ddbbafba103549bf803e but make links readonly.

**Comment by jokokko** [comment]
Cheers! I appreciate the feedback & PR. I made a bunch of fixes & restructuring, so I incorporated this in the form of disabling page action on _about:*_ URIs.
